name: Запуск ChatGPT

on:
  push:
    branches:
      - main

jobs:
  run-chat:
    runs-on: ubuntu-latest
    env:
      HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}   # сюда вставь свой секрет с токеном
      PROMPT: "Привет, как дела?"                # сюда вставь свой вопрос
    steps:
      - uses: actions/checkout@v3
      - name: Установка Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Установка зависимостей
        run: pip install requests
      - name: Запуск скрипта
        run: python chat.py
